#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname $0)" || exit; pwd)
eval "$(cat ${SCRIPT_DIR}/.env.local <(echo) <(declare -x))"

GITHUB_OWNER=${GITHUB_OWNER}
GITHUB_REPO=${GITHUB_REPO}
GITHUB_APP_INFO_SECRET_NAME=${GITHUB_APP_INFO_SECRET_NAME}
GITHUB_APP_ID=${GITHUB_APP_ID}
GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID}
[ -n "${AWS_PROFILE}" ] && AWS_CLI_OPTIONS="--profile ${AWS_PROFILE}"


yarn cdk deploy ${AWS_CLI_OPTIONS} \
  --require-approval never \
  -c GITHUB_OWNER=${GITHUB_OWNER} \
  -c GITHUB_REPO=${GITHUB_REPO} \
  -c GITHUB_APP_INFO_SECRET_NAME=${GITHUB_APP_INFO_SECRET_NAME} \
  -c GITHUB_APP_ID=${GITHUB_APP_ID} \
  -c GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID}
